// src/app/telegram/components/telegram-app/telegram-app.component.ts
import { Component, Input } from '@angular/core';
import { TelegramTheme } from '../../../lib/telegram-theme';

@Component({
  selector: 'telegram-app',
  templateUrl: './telegram-app.component.html',
  styleUrls: ['./telegram-app.component.scss']
})
export class TelegramAppComponent {
  @Input() theme: TelegramTheme;
  sidebarOpen = false;

  toggleSidebar() {
    this.sidebarOpen = !this.sidebarOpen;
  }
}

<telegram-sidebar [open]="sidebarOpen"></telegram-sidebar>
<telegram-chats-list fxFlex="1 2 100%"></telegram-chats-list>
<telegram-chat-view fxFlex="1 1 100%"></telegram-chat-view>

// src/components/ThemePreview/components/TelegramApp/TelegramApp.tsx
import './TelegramApp.scss';
import * as React from 'react';
import { Component } from 'react';
import { TelegramTheme } from '../../../../lib/TelegramTheme';

export default class TelegramApp extends Component<{
  theme: TelegramTheme;
}, {
    welcome?: boolean;
    showSidebar?: boolean;
  }> {
  state = {
    welcome: false,
    showSidebar: false
  };

  toggleSidebar = () => this.setState({ showSidebar: !this.state.showSidebar });

  renderContent() {
    const {showSidebar, welcome} = this.state;
    if (welcome) {
      return <div className='telegram-welcome'>
        <header>header</header>
        <main>
          <section>
            <h2>Telegram Desktop</h2>
            <p>Weolcome to unofficial telegram UI emulator.</p>
          </section>
        </main>
      </div>;
    } else {
      return [<div
        className={`telegram-sidebar-container${showSidebar ? '' : ' hidden'}`}
        onClick={this.toggleSidebar}
      >
        <div className='telegram-sidebar'>
          sidebar
        </div>
      </div>,
      <div className='telegram-chats-list'>
        <button onClick={this.toggleSidebar}></button>
      </div>,
      <div className='telegram-chat-view'>chats view</div>
      ];
    }
  }

  render() {
    const {showSidebar} = this.state;
    return <div className='telegram-app'>
      {this.renderContent()}
    </div>;
  }
}
